import ClerkProviderWithFonts from "./ClerkProviderWithFonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProviderWithFonts>
          {children}
        </ClerkProviderWithFonts>
      </body>
    </html>
  );
}
